### ISSUE TITLE
Animated GIF or Video

### ISSUE THREAD

**Issue by thombergs** [pschild/CodeRadarVisualization#46]
It would be a cool feature to be able to automatically make a picture for each commit and combine them in an animated GIF or a movie. This has no real analytical value but it would explicitly show the evolution of a project which would be a gimmick in every presentation :).

**Comment by pschild** [comment]
Alles possible library for that could be https://github.com/eugeneware/gifencoder

**Comment by pschild** [comment]
This issue is now fixed in branch angular-ui.
